version: '3'
services:
  go:
    container_name: go
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app/:/go/src/app
    ports: 
      - "5000:5000"
    environment:
      PGHOST: postgres
    tty: true
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080